#! /usr/bin/sh

# Settings from /etc/sysconfig/filename are available as environment vars
# with the name 'SYS__FILENAME__KEY' (filename converted to upper case).
#
# Not all files are parsed, current list is:
#   bootloader, language
#

# usage: get-default
#
# Read the default boot entry.
#
# The entry is written into the file passed via 'PBL_RESULT' environment var.
# Nothing is returned if no default is set.

# include common functions
. "$PBL_INCLUDE/library"

lib_get_efi_mount_dir

# the EFI variable wins, loader.conf is what is left on a system booted
# without one
entry=$(lib_efi_var_get LoaderEntryDefault)

if [ -z "$entry" ] ; then
  entry=$(lib_loader_conf_get "$efi_mount_dir/loader/loader.conf" default)
fi

if [ -n "$entry" ] ; then
  echo "$entry" >> "$PBL_RESULT"
fi

exit 0
